- name: Instalar certbot
  ansible.builtin.apt:
    name: certbot
    state: present
  when: ansible_os_family == "Debian"

- name: Criar certificado autoassinado
  ansible.builtin.command: > # Ou use 'shell' se o comando tiver pipes, redirecionamentos, etc.
    openssl req -x509 -nodes -days 365
    -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key
    -out /etc/ssl/certs/apache-selfsigned.crt
  args:
    creates: /etc/ssl/certs/apache-selfsigned.crt

- name: Configurar Apache para usar SSL
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    insertafter: "^<VirtualHost *:80>"
    line: |
      SSLEngine on
      SSLCertificateFile /etc/ssl/certs/glpi.crt
      SSLCertificateKeyFile /etc/ssl/private/glpi.key
  notify: Reiniciar Apache
  when: ansible_os_family == "Debian"

- name: Ativar módulo SSL
  command: a2enmod ssl
  notify: Reiniciar Apache
  when: ansible_os_family == "Debian"

- name: Ativar site SSL
  command: a2ensite default-ssl
  notify: Reiniciar Apache
  when: ansible_os_family == "Debian"

# Handlers
- name: Reiniciar Apache
  service:
    name: apache2
    state: restarted
