[glpi]
lab-zero-trust-glpi ansible_connection=community.docker.docker

[localhost]
127.0.0.1 ansible_connection=local
[mariadb]
lab-zero-trust-mariadb


[all:vars]
ansible_user=minicurso
ansible_private_key_file=~/.ssh/id_rsa
